# docker-compose.yaml
version: '3'
services:
  auth-service:
    build: ./auth-service
    ports:
      - "8000:8000"
  product-service:
    build: ./product-service
    ports:
      - "8001:8001"
  user-service:
    build: ./user-service
    ports:
      - "8002:8002"
